description: WRN, AT, small eps AT 3steps batch-size 512 

target:
  # which virtual cluster you belong to (msrlabs, etc.).
  vc: resrchvc
  cluster: rr1
  # vc: msrlabs
  # use an Azure cluster (eu1, eu2, ...)
  # cluster: eu1

environment:
  # image: hadisalman/smoothing:latest
  # image: hadisalman/robustness:latest
  image: hadisalman/robustness:1.3-cuda10.1-cudnn7-devel

# # azure storage configuration
storage:
  imagenet:
    storage_account_name: robustnessws4285631339
    container_name: blackbox-smoothing

  my_output:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_output
    is_output: True

  my_data:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_data

code:
  # upload the code
  local_dir: $CONFIG_DIR/../

data:
  storage_id: my_data
#   # don't forget to run with --upload-data
#   local_dir: $CONFIG_DIR/datasets_and_models/

#   # The data will be uploaded to your _default storage.
#   #   Check ``multi_storage.yaml'' for more flexibility.
#   remote_dir: datasets_and_models

# schedule two simple jobs, names for each job should be different:
jobs:
## ResNet-50


# WRN
- name: wide_resnet50_2_batch512_3steps_eps0.01_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.01 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.01 
          --attack-lr 0.006
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1



- name: wide_resnet50_2_batch512_3steps_eps0.02_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.02 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.02 
          --attack-lr 0.012
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1



- name: wide_resnet50_2_batch512_3steps_eps0.03_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.03 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.03 
          --attack-lr 0.018
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1




- name: wide_resnet50_2_batch512_3steps_eps0.04_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.04 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.04 
          --attack-lr 0.024
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1



- name: wide_resnet50_2_batch512_3steps_eps0.05_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.05 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.05 
          --attack-lr 0.030
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1




- name: wide_resnet50_2_batch512_3steps_eps0.1_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.1 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.1 
          --attack-lr 0.060
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1




- name: wide_resnet50_2_batch512_3steps_eps0.15_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.15 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.15 
          --attack-lr 0.090
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1




- name: wide_resnet50_2_batch512_3steps_eps0.2_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 16gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.2 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.2 
          --attack-lr 0.12
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1





- name: wide_resnet50_2_batch512_3steps_eps0.25_wd_1e-4
  sku: G4
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.25 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.25 
          --attack-lr 0.166
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1





- name: wide_resnet50_2_batch512_3steps_eps0.30_wd_1e-4
  sku: G4
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.30 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.30 
          --attack-lr 0.20
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1





- name: wide_resnet50_2_batch512_3steps_eps0.40_wd_1e-4
  sku: G4
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.40 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.40 
          --attack-lr 0.26
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1




- name: wide_resnet50_2_batch512_3steps_eps0.50_wd_1e-4
  sku: G4
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/imagenet_experiments/wide_resnet50_2/ 
          --resume 
          --exp-name wide_resnet50_2_batch512_3steps_eps0.50 
          --constraint 2
          --attack-steps 3 
          --adv-train 1 
          --eps 0.50 
          --attack-lr 0.33
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 8
          --lr 0.1


