description: Training imagenet classifiers

target:
  # which virtual cluster you belong to (msrlabs, etc.).
  vc: resrchvc
  cluster: rr1
  # vc: msrlabs
  # use an Azure cluster (eu1, eu2, ...)
  # cluster: eu1

environment:
  # image: hadisalman/smoothing:latest
  # image: hadisalman/robustness:latest
  image: hadisalman/robustness:1.3-cuda10.1-cudnn7-devel

# # azure storage configuration
storage:
  imagenet:
    storage_account_name: robustnessws4285631339
    container_name: blackbox-smoothing

  my_output:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_output
    is_output: True

  my_data:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_data

code:
  # upload the code
  local_dir: $CONFIG_DIR/../

data:
  storage_id: my_data
#   # don't forget to run with --upload-data
#   local_dir: $CONFIG_DIR/datasets_and_models/

#   # The data will be uploaded to your _default storage.
#   #   Check ``multi_storage.yaml'' for more flexibility.
#   remote_dir: datasets_and_models

# schedule two simple jobs, names for each job should be different:
jobs:              

- name: alexnet_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch alexnet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name alexnet_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: alexnet_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch alexnet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name alexnet_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: vgg16_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch vgg16 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name vgg16_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: vgg16_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch vgg16 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name vgg16_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: vgg16_bn_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch vgg16_bn 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name vgg16_bn_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: vgg16_bn_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch vgg16_bn 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name vgg16_bn_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: squeezenet_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch squeezenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name squeezenet_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: squeezenet_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch squeezenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name squeezenet_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: densenet_batch128_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch densenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 128
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name densenet_batch128_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: densenet_batch128_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch densenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 128
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name densenet_batch128_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: shufflenet_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch shufflenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name shufflenet_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: shufflenet_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch shufflenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name shufflenet_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: mobilenet_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch mobilenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name mobilenet_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: mobilenet_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch mobilenet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name mobilenet_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: resnext50_32x4d_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch resnext50_32x4d 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name resnext50_32x4d_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: resnext50_32x4d_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch resnext50_32x4d 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name resnext50_32x4d_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1



- name: mnasnet_batch256_3steps_eps3
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch mnasnet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name mnasnet_batch256_3steps_eps3
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 1
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


- name: mnasnet_batch256_3steps_eps0
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
        --arch mnasnet 
        --dataset imagenet 
        --data /mnt/imagenet/datasets/imagenet_zipped 
        --batch-size 256
        --out-dir /mnt/my_output/imagenet_experiments/vary_arch 
        --resume 
        --exp-name mnasnet_batch256_3steps_eps0
        --epochs 90
        --step-lr 30
        --weight-decay 1e-4
        --adv-train 0
        --constraint 2
        --attack-steps 3 
        --eps 3.0 
        --attack-lr 2.0
        --workers 20
        --log-iters 1
        --lr 0.1


