description: ResNet-50 and WRN, AT, sweep eps AT 3steps (values larger that 12), stepLR, wd 5e-4,1e-4,1e-5, batch-size 512 

target:
  # which virtual cluster you belong to (msrlabs, etc.).
  vc: resrchvc
  cluster: rr1
  # vc: msrlabs
  # use an Azure cluster (eu1, eu2, ...)
  # cluster: eu1

environment:
  # image: hadisalman/smoothing:latest
  # image: hadisalman/robustness:latest
  image: hadisalman/robustness:1.3-cuda10.1-cudnn7-devel

# # azure storage configuration
storage:
  imagenet:
    storage_account_name: msrairesidentssa8
    container_name: imagenet

  my_output:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_output
    is_output: True

  my_data:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_data

code:
  # upload the code
  local_dir: $CONFIG_DIR/../

data:
  storage_id: my_data
#   # don't forget to run with --upload-data
#   local_dir: $CONFIG_DIR/datasets_and_models/

#   # The data will be uploaded to your _default storage.
#   #   Check ``multi_storage.yaml'' for more flexibility.
#   remote_dir: datasets_and_models

# schedule two simple jobs, names for each job should be different:
jobs:
## ResNet-50
- name: resnet50_batch512_3steps_eps20_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id resnet50_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: resnet50_batch512_3steps_eps50_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id resnet50_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: resnet50_batch512_3steps_eps75_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id resnet50_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: resnet50_batch512_3steps_eps100_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id resnet50_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0



## WRN

- name: wrn_batch512_3steps_eps20_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id wrn_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: wrn_batch512_3steps_eps50_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id wrn_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: wrn_batch512_3steps_eps75_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id wrn_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: wrn_batch512_3steps_eps100_wd_1e-5
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-5 
              --outdir /mnt/my_output/wd_1e-5/ --resume --exp-id wrn_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0




# wd 1e-4 
## ResNet-50
- name: resnet50_batch512_3steps_eps20_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: resnet50_batch512_3steps_eps50_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: resnet50_batch512_3steps_eps75_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: resnet50_batch512_3steps_eps100_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0



## WRN

- name: wrn_batch512_3steps_eps20_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: wrn_batch512_3steps_eps50_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: wrn_batch512_3steps_eps75_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: wrn_batch512_3steps_eps100_wd_1e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 1e-4 
              --outdir /mnt/my_output/wd_1e-4/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0






# wd 5e-4 
## ResNet-50
- name: resnet50_batch512_3steps_eps20_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: resnet50_batch512_3steps_eps50_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: resnet50_batch512_3steps_eps75_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: resnet50_batch512_3steps_eps100_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch resnet50 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_resnet50_3steps_sweep_eps/ --resume --exp-id resnet50_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0



## WRN

- name: wrn_batch512_3steps_eps20_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps20 --num-steps 3 --AT --eps 20.0 --attack-lr 13.0


- name: wrn_batch512_3steps_eps50_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps50 --num-steps 3 --AT --eps 50.0 --attack-lr 30.0


- name: wrn_batch512_3steps_eps75_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps75 --num-steps 3 --AT --eps 75.0 --attack-lr 40.0


- name: wrn_batch512_3steps_eps100_wd_5e-4
  sku: G4
  command:
  - python my_main.py --arch wide_resnet50_2 --dataset imagenet --data-path /mnt/imagenet --batch-size 512 --weight-decay 5e-4 
              --outdir /mnt/my_output/adversarial_training_stepLR_wrn_3steps_sweep_eps/ --resume --exp-id wrn_batch512_3steps_eps100 --num-steps 3 --AT --eps 100.0 --attack-lr 60.0

