description: Training imagenet classifiers

target:
  # which virtual cluster you belong to (msrlabs, etc.).
  vc: resrchvc
  cluster: rr1
  # vc: msrlabs
  # use an Azure cluster (eu1, eu2, ...)
  # cluster: eu1

  
environment:
  # image: hadisalman/smoothing:latest
  # image: hadisalman/robustness:latest
  image: hadisalman/robustness:1.3-cuda10.1-cudnn7-devel

# # azure storage configuration
storage:
  imagenet:
    storage_account_name: robustnessws4285631339
    container_name: blackbox-smoothing

  my_output:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_output
    is_output: True

  my_data:
    # Replace with the name of the Azure Storage Account you created.
    #   If you followed the tutorial, this should be your_username
    storage_account_name: robustnessws4285631339
    # Specify a name of the container on your blob (ex. phillytools),
    #   to store data, results and code. It will be created if it does not exist.
    container_name: madrylab
    # You can optionally specify a mount_path that will be directly accessible
    #   by your jobs. By default it's:
    mount_dir: /mnt/my_data

code:
  # upload the code
  local_dir: $CONFIG_DIR/../

data:
  storage_id: my_data
#   # don't forget to run with --upload-data
#   local_dir: $CONFIG_DIR/datasets_and_models/

#   # The data will be uploaded to your _default storage.
#   #   Check ``multi_storage.yaml'' for more flexibility.
#   remote_dir: datasets_and_models

# schedule two simple jobs, names for each job should be different:
jobs:       
#### Clean Models
- name: wrn1_batch512_3steps_eps0_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch resnet50 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/wrn_vary_width/ 
          --resume 
          --exp-name wrn1_eps0 
          --adv-train 0
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 20
          --lr 0.1


- name: wrn2_batch512_3steps_eps0_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_2 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/wrn_vary_width/ 
          --resume 
          --exp-name wrn2_eps0 
          --adv-train 0
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 20
          --lr 0.1

- name: wrn3_batch512_3steps_eps0_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_3 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/wrn_vary_width/ 
          --resume 
          --exp-name wrn3_eps0 
          --adv-train 0
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 20
          --lr 0.1

          
- name: wrn4_batch512_3steps_eps0_wd_1e-4
  sku: G4
  submit_args:
    container_args:
      shm_size: 64gb  
  command:
    - lscpu
    - df -h /dev/shm
    - python main_trainer.py 
          --arch wide_resnet50_4 
          --dataset imagenet 
          --data /mnt/imagenet/datasets/imagenet_zipped 
          --batch-size 512 
          --weight-decay 1e-4     
          --out-dir /mnt/my_output/wrn_vary_width/ 
          --resume 
          --exp-name wrn4_eps0 
          --adv-train 0
          --log-iter 1
          --epochs 90
          --step-lr 30
          --workers 20
          --lr 0.1



##### Robust Models
# - name: wrn1_3steps_eps11
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps11 
#           --num-steps 3 
#           --AT 
#           --eps 11.0 
#           --attack-lr 8.0

# - name: wrn1_3steps_eps9
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps9 
#           --num-steps 3 
#           --AT 
#           --eps 9.0 
#           --attack-lr 7.0


# - name: wrn1_3steps_eps7
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps7 
#           --num-steps 3 
#           --AT 
#           --eps 7.0 
#           --attack-lr 5.0


# - name: wrn1_3steps_eps5
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps5 
#           --num-steps 3 
#           --AT 
#           --eps 5.0 
#           --attack-lr 3.0


# - name: wrn1_3steps_eps3
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps3 
#           --num-steps 3 
#           --AT 
#           --eps 3.0 
#           --attack-lr 2.0

# - name: wrn1_3steps_eps1
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch resnet50 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn1_eps1 
#           --num-steps 3 
#           --AT 
#           --eps 1.0 
#           --attack-lr 0.8





# - name: wrn2_3steps_eps11
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps11 
#           --num-steps 3 
#           --AT 
#           --eps 11.0 
#           --attack-lr 8.0

# - name: wrn2_3steps_eps9
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps9 
#           --num-steps 3 
#           --AT 
#           --eps 9.0 
#           --attack-lr 7.0


# - name: wrn2_3steps_eps7
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps7 
#           --num-steps 3 
#           --AT 
#           --eps 7.0 
#           --attack-lr 5.0


# - name: wrn2_3steps_eps5
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps5 
#           --num-steps 3 
#           --AT 
#           --eps 5.0 
#           --attack-lr 3.0


# - name: wrn2_3steps_eps3
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps3 
#           --num-steps 3 
#           --AT 
#           --eps 3.0 
#           --attack-lr 2.0

# - name: wrn2_3steps_eps1
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_2 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn2_eps1 
#           --num-steps 3 
#           --AT 
#           --eps 1.0 
#           --attack-lr 0.8

              



# - name: wrn3_3steps_eps11
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps11 
#           --num-steps 3 
#           --AT 
#           --eps 11.0 
#           --attack-lr 8.0

# - name: wrn3_3steps_eps9
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps9 
#           --num-steps 3 
#           --AT 
#           --eps 9.0 
#           --attack-lr 7.0


# - name: wrn3_3steps_eps7
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps7 
#           --num-steps 3 
#           --AT 
#           --eps 7.0 
#           --attack-lr 5.0


# - name: wrn3_3steps_eps5
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps5 
#           --num-steps 3 
#           --AT 
#           --eps 5.0 
#           --attack-lr 3.0


# - name: wrn3_3steps_eps3
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps3 
#           --num-steps 3 
#           --AT 
#           --eps 3.0 
#           --attack-lr 2.0

# - name: wrn3_3steps_eps1
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_3 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn3_eps1 
#           --num-steps 3 
#           --AT 
#           --eps 1.0 
#           --attack-lr 0.8


              

# - name: wrn4_3steps_eps11
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps11 
#           --num-steps 3 
#           --AT 
#           --eps 11.0 
#           --attack-lr 8.0

# - name: wrn4_3steps_eps9
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps9 
#           --num-steps 3 
#           --AT 
#           --eps 9.0 
#           --attack-lr 7.0


# - name: wrn4_3steps_eps7
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps7 
#           --num-steps 3 
#           --AT 
#           --eps 7.0 
#           --attack-lr 5.0


# - name: wrn4_3steps_eps5
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps5 
#           --num-steps 3 
#           --AT 
#           --eps 5.0 
#           --attack-lr 3.0


# - name: wrn4_3steps_eps3
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps3 
#           --num-steps 3 
#           --AT 
#           --eps 3.0 
#           --attack-lr 2.0

# - name: wrn4_3steps_eps1
#   sku: G4
#   submit_args:
#     container_args:
#       shm_size: 64gb  

#   command:
#   - python my_main.py 
#           --arch wide_resnet50_4 
#           --dataset imagenet 
#           --data /mnt/imagenet/datasets/imagenet_zipped 
#           --batch-size 256     
#           --outdir /mnt/my_output/wrn_vary_width/ 
#           --resume 
#           --exp-id wrn4_eps1 
#           --num-steps 3 
#           --AT 
#           --eps 1.0 
#           --attack-lr 0.8


                            